### ISSUE TITLE
Makefile compile error for windows on ubuntu 16.04

### ISSUE THREAD

**Issue by maddenode** [XDNA-Core/XDNA#5]
… re-open an accidentally. sorry.

**Comment by maddenode** [comment]
… re-open an accidentally. sorry.

**Comment by XDNA-Core** [comment]
Anyway. Win32 and win64 versions compiles from scratch without any need in changes from your side. 
Try to clone latest version of code to rewrite your changes. 
Try to use ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 co configure. 
But I want warn you that win64 version is unworkable for now and there is a great chance that you`ve wasting your time. This version is not in our priority goals for now.
