### ISSUE TITLE
fyi - macOS - majove crash

### ISSUE THREAD

**Issue by johndpope** [XDNA-Core/XDNA#6]
Process:               XDNA-Qt [7359]
Path:                  /Applications/XDNA-Qt.app/Contents/MacOS/XDNA-Qt
Identifier:            io.xdna.XDNA-Qt
Version:               1.1.0 (1.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           XDNA-Qt [7359]
User ID:               501

Date/Time:             2018-08-14 19:43:31.749 -0400
OS Version:            Mac OS X 10.14 (18A347e)
Report Version:        12
Anonymous UUID:        69E5B713-0D37-0881-6D11-FBF9FFEF072F

Sleep/Wake UUID:       301DD28C-E705-41E1-8EE3-AF7F8477841F

Time Awake Since Boot: 12000 seconds
Time Since Wake:       400 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/XDNA-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10dd23000 -        0x10e5a8ff7 +io.xdna.XDNA-Qt (1.1.0 - 1.1.0) <E9085A57-2FDD-3AA0-A74D-E67C10A1C047> /Applications/XDNA-Qt.app/Contents/MacOS/XDNA-Qt
       0x10e661000 -        0x10e6b8ff7 +libzmq.5.dylib (0) <177948E4-6B87-3FB4-8E9F-2501F466E7B7> /Applications/XDNA-Qt.app/Contents/Frameworks/libzmq.5.dylib
       0x10e6c7000 -        0x10e6c9ff7 +libboost_system.dylib (0) <6D4202B3-758D-3014-A208-8577024B9BB3> /Applications/XDNA-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10e6cd000 -        0x10e6dcff7 +libboost_filesystem.dylib (0) <BDEC6C74-6778-342E-AFF0-62ABA7D03E43> /Applications/XDNA-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10e6e5000 -        0x10e717fff +libboost_program_options-mt.dylib (0) <AEDAEFBB-E939-3404-BD07-2313425473FA> /Applications/XDNA-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10e734000 -        0x10e741fff +libboost_thread-mt.dylib (0) <CE22F73C-D5EA-32D9-A732-D824D54D622C> /Applications/XDNA-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10e74b000 -        0x10e74eff7 +libboost_chrono-mt.dylib (0) <19312DE7-D906-321B-9A48-5822E962A2EB> /Applications/XDNA-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10e752000 -        0x10e859ff7 +QtNetwork (5.5.1) <883A53FB-7857-34BC-B732-F23592EA3B26> /Applications/XDNA-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10e88f000 -        0x10ed86ff7 +QtWidgets (5.5.1) <51985D53-4933-38E5-A842-DC85D15F5F8C> /Applications/XDNA-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10eebc000 -        0x10f34eff7 +QtGui (5.5.1) <5C681010-C0B3-36D9-BD77-3BDC232EF97F> /Applications/XDNA-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10f42c000 -        0x10f92bff7 +QtCore (5.5.1) <73946C22-5E05-3FD4-B5D5-B0DBCD039222> /Applications/XDNA-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10f9b8000 -        0x10fa1aff7 +QtDBus (5.5.1) <27A55C14-E871-3DBE-8538-87D711FFAB35> /Applications/XDNA-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x10fa2f000 -        0x10fb59ff3 +libprotobuf.16.dylib (0) <430E7C4E-08C7-351B-9392-823C2791C091> /Applications/XDNA-Qt.app/Contents/Frameworks/libprotobuf.16.dylib
       0x10fc09000 -        0x10fd23ff3 +libdb_cxx-4.8.dylib (0) <A961AAB6-ED4B-36F5-846E-F8B24D4FFFC8> /Applications/XDNA-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x10fd5b000 -        0x10fd9afff +libssl.1.0.0.dylib (0) <4D343D8E-B72A-38BD-9204-CC0354C0B7F8> /Applications/XDNA-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x10fdb6000 -        0x10fdbeffb +libminiupnpc.17.dylib (0) <D83B2C71-0CFC-3324-92DC-ACD64DF63142> /Applications/XDNA-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x10fdc2000 -        0x10fdc3fff +libevent_pthreads-2.1.6.dylib (0) <32AC3368-70B7-32B4-8465-50FA643C2649> /Applications/XDNA-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x10fdc6000 -        0x10fdf2ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/XDNA-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x10fdff000 -        0x10ff6fd67 +libcrypto.1.0.0.dylib (0) <4A0A66FE-A6B9-387F-B265-512C91DF46F9> /Applications/XDNA-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x11b4e4000 -        0x11b562347  dyld (625.6) <EDA601EE-2445-33D5-81D8-FC44EB952B58> /usr/lib/dyld
    0x7fff4983a000 -     0x7fff4a64bfff  com.apple.AppKit (6.9 - 1651.10.100) <5D2C3768-AC79-336C-907A-89FD2745A039> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4a69d000 -     0x7fff4a69dfff  com.apple.ApplicationServices (50.1 - 50.1) <9D9D0F5F-7508-312F-AD33-9B64F36EDFDF> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4c2ac000 -     0x7fff4c6fafef  com.apple.CoreFoundation (6.9 - 1548.11.1) <51153FC6-2B19-3D56-BA10-E61A2899BF7E> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4d5ef000 -     0x7fff4d5effff  com.apple.CoreServices (929.2 - 929.2) <19CBE74E-8F1C-3271-A8C9-2EEC28CD547F> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4e70e000 -     0x7fff4eadcffb  com.apple.Foundation (6.9 - 1548.11.1) <69241F6D-EBF5-3E0C-966D-818CD5390A26> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff76c87000 -     0x7fff76c88ffb  libSystem.B.dylib (1252.200.5) <885B64EC-2F28-3731-AE0E-05194CCFC60F> /usr/lib/libSystem.B.dylib
    0x7fff76ee4000 -     0x7fff76f3bfff  libc++.1.dylib (400.9.4) <54E021AB-C993-3B7F-8FA0-4D3555C22EE0> /usr/lib/libc++.1.dylib
    0x7fff76f3c000 -     0x7fff76f52ff7  libc++abi.dylib (400.16) <6D3E0AB1-9C73-381D-80DF-9D1F2AF26520> /usr/lib/libc++abi.dylib
    0x7fff7872d000 -     0x7fff78eb3fe7  libobjc.A.dylib (750) <488809D2-8FF9-3515-A4DA-DCDE8C7A73EA> /usr/lib/libobjc.A.dylib
    0x7fff79692000 -     0x7fff79696fff  libcache.dylib (81) <C3B4C040-EA3E-31FB-92C4-81B24947C0D1> /usr/lib/system/libcache.dylib
    0x7fff79697000 -     0x7fff796a1fff  libcommonCrypto.dylib (60118.200.6) <EC475400-987F-3B56-A945-86B8CC8B5ABC> /usr/lib/system/libcommonCrypto.dylib
    0x7fff796a2000 -     0x7fff796a9fff  libcompiler_rt.dylib (63.4) <A0F6B15E-FDDB-370D-BE7F-B139BE924FED> /usr/lib/system/libcompiler_rt.dylib
    0x7fff796aa000 -     0x7fff796b3ffb  libcopyfile.dylib (146.200.2) <C6CD6BCC-F447-3D92-8698-DAF731E525C5> /usr/lib/system/libcopyfile.dylib
    0x7fff796b4000 -     0x7fff79738fdb  libcorecrypto.dylib (602.200.49) <65D8F4DF-FF5A-3ABF-80D2-4B8A87A4A702> /usr/lib/system/libcorecrypto.dylib
    0x7fff797be000 -     0x7fff797f8fff  libdispatch.dylib (1008.200.77) <B6941F52-C5C1-391A-BE5D-FF8927C14EF2> /usr/lib/system/libdispatch.dylib
    0x7fff797f9000 -     0x7fff79827fff  libdyld.dylib (625.6) <6F5D19BE-79F1-33D5-98D6-F1B180A29545> /usr/lib/system/libdyld.dylib
    0x7fff79828000 -     0x7fff79828ffb  libkeymgr.dylib (30) <3EE2396C-93C8-30CA-AE90-288D7E6E47CC> /usr/lib/system/libkeymgr.dylib
    0x7fff79836000 -     0x7fff79836ff7  liblaunch.dylib (1336.200.95) <B850292D-87E7-363A-B1C7-91AF6D44B624> /usr/lib/system/liblaunch.dylib
    0x7fff79837000 -     0x7fff7983cfff  libmacho.dylib (917) <6CECE015-3F83-321E-A746-155FA4594DB7> /usr/lib/system/libmacho.dylib
    0x7fff7983d000 -     0x7fff7983ffff  libquarantine.dylib (86.200.10) <02B3CF2B-0440-3225-ACC8-3678E5A314BB> /usr/lib/system/libquarantine.dylib
    0x7fff79840000 -     0x7fff79841ff3  libremovefile.dylib (45.200.2) <DDB2F4D9-0B7E-33C8-AC20-B901D1F76E7D> /usr/lib/system/libremovefile.dylib
    0x7fff79842000 -     0x7fff79859ff7  libsystem_asl.dylib (356.200.4) <7C4A84BE-D943-3D02-8A7E-CA5C36508B02> /usr/lib/system/libsystem_asl.dylib
    0x7fff7985a000 -     0x7fff7985afff  libsystem_blocks.dylib (73) <72C1806F-CEF6-3C0F-AD11-D113CA18E2A0> /usr/lib/system/libsystem_blocks.dylib
    0x7fff7985b000 -     0x7fff798e3fff  libsystem_c.dylib (1272.200.25) <4A9EB86D-3844-3704-AA23-58A1D34474BE> /usr/lib/system/libsystem_c.dylib
    0x7fff798e4000 -     0x7fff798e7ffb  libsystem_configuration.dylib (963.200.27) <FBCB6C98-E3D0-3676-B09B-B492A3B0996D> /usr/lib/system/libsystem_configuration.dylib
    0x7fff798e8000 -     0x7fff798ebff3  libsystem_coreservices.dylib (64) <3AE8166D-60D5-3E04-AF3E-349C868365E1> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff798ec000 -     0x7fff798f2ffb  libsystem_darwin.dylib (1272.200.25) <D57DA77F-31ED-3E25-AF32-AD8EAA8686D6> /usr/lib/system/libsystem_darwin.dylib
    0x7fff798f3000 -     0x7fff798f9ff7  libsystem_dnssd.dylib (878.200.35) <619630E8-0C71-300A-ABFD-B6BE1DE35B07> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff798fa000 -     0x7fff79946ffb  libsystem_info.dylib (517.200.9) <F8E24371-0C2F-3FD8-953A-FAC8AEFFF5D0> /usr/lib/system/libsystem_info.dylib
    0x7fff79947000 -     0x7fff7996eff7  libsystem_kernel.dylib (4903.200.327) <97FBB87B-D70D-3745-BA1E-A1EE81F0F47A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7996f000 -     0x7fff799baffb  libsystem_m.dylib (3158.200.7) <D4FD7BEA-762C-3F87-B2C2-8B3A1EE75483> /usr/lib/system/libsystem_m.dylib
    0x7fff799bb000 -     0x7fff799dffff  libsystem_malloc.dylib (166.200.56) <FD750ED7-318F-36AC-B0BC-2AB94EEAF47B> /usr/lib/system/libsystem_malloc.dylib
    0x7fff799e0000 -     0x7fff799ebff3  libsystem_networkextension.dylib (767.200.39) <E0AE6251-DF4D-32B4-832F-24C398497683> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff799ec000 -     0x7fff799f3fff  libsystem_notify.dylib (172.200.21) <5662E0A8-AC01-351E-AB27-2095364A55C6> /usr/lib/system/libsystem_notify.dylib
    0x7fff799f4000 -     0x7fff799fdff7  libsystem_platform.dylib (177.200.14) <7852E4E7-56A4-31EA-87D0-623E84EB1534> /usr/lib/system/libsystem_platform.dylib
    0x7fff799fe000 -     0x7fff79a08ff7  libsystem_pthread.dylib (330.200.45) <1A440BF0-CAA6-3BC4-8700-4FE24D2AA39C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff79a09000 -     0x7fff79a0cffb  libsystem_sandbox.dylib (851.200.142) <C59F6850-9EEF-31EA-9D2C-05CF3A4ED653> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff79a0d000 -     0x7fff79a0fff3  libsystem_secinit.dylib (30.200.11.51.1) <2A51EF81-1141-303E-8895-ED79A396C356> /usr/lib/system/libsystem_secinit.dylib
    0x7fff79a10000 -     0x7fff79a17ff7  libsystem_symptoms.dylib (820.207.88) <63057D4C-B9E4-337C-9EBC-546706BE135D> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff79a18000 -     0x7fff79a2dff7  libsystem_trace.dylib (906.200.78) <83663488-AE72-37EF-B266-102B36B8088D> /usr/lib/system/libsystem_trace.dylib
    0x7fff79a2f000 -     0x7fff79a34ffb  libunwind.dylib (35.4) <87D90D7D-57C1-3D8B-8C87-F78DCE6BBDEC> /usr/lib/system/libunwind.dylib
    0x7fff79a35000 -     0x7fff79a65ff7  libxpc.dylib (1336.200.95) <1E87BF5D-CFEB-34C3-9E68-5833AB753788> /usr/lib/system/libxpc.dylib

**Comment by johndpope** [comment]
this was working fine on my other osx machine high sierra. not sure why it's not finding dylib.

**Comment by altec404** [comment]
I think you have to install libboost.
If you already installed Xcode Command Line Tools and  home brew ,


brew doctor
brew install boost

**Comment by johndpope** [comment]
thx

**Comment by johndpope** [comment]
Probably should embed boostframeworks with build. Haven’t dived into code but if it’s using Xcode project it’s pretty trivial to do.
